version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: always

  cortex:
    image: thehiveproject/cortex:3.1.1
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
    command:
      --analyzer-url /opt/cortex/analyzers
    volumes:
      - ./vol/cortex/Cortex-Analyzers/analyzers:/opt/cortex/analyzers
#      - ./vol/cortex/application.conf:/opt/cortex/conf/application.conf
    restart: always